### PR TITLE
1.9 Extensions

### PR DESCRIPTION
**Pull request by longemen3000**
adds `BlockArrays`, `DataFrames`, `LazyArrays`, `OnlineStatsBase`, `Referenceables` as extensions. lets start with those, and if tests pass, then add the unconditional dependencies as extensions.

### CODE REVIEW

**Comment by longemen3000** [comment]
I would really benefit for testing 1.9 here 😅, as the only version that uses extensions is nightly, and it seems to have an error that i cannot reproduce on 1.9

**Comment by longemen3000** [comment]
for some reason, the inference test on `Referenceables.referenceable` is failing

**Comment by MasonProtter** [comment]
Ugh, I'm sorry, I tried to switch away from the old CI infrastructure hoping that might make this easier but it seems to have just introduced a new nest of problems. Maybe just rewind your branch to before my commits.

**Comment by longemen3000** [comment]
@MasonProtter tests pass (with the new CI). There was a genuine bug on 32 bit that was fixed and another on OnlineStatsBase. Can we merge this?

**Comment by MasonProtter** [comment]
Awesome, thank you @longemen3000!

**Pull request merged**
