### PR TITLE
bump Adapt compat

### PR DESCRIPTION
**Pull request by jeremiedb**
Add compat entry for Adapt v4. Notably needed by Flux: https://github.com/FluxML/Flux.jl/pull/2362

### CODE REVIEW

**Comment by christiangnrd** [comment]
Seems like this forces [Referenceables.jl](https://github.com/tkf/Referenceables.jl) down to 0.1.0 (before it supported Adapt) which is causing the errors. Odds of it getting compat support merged seem like basically zero, but since Referenceables support is from an extension, and this PR keeps support for lower versions of Adapt that won't cause those errors, I think this is fine to merge.

**Comment by jeremiedb** [comment]
@MasonProtter Is it reasonable to add https://github.com/tkf/Referenceables.jl to the `JuliaFolds2` org? 
It looks like a fairly lightweight package and having it into `JuliaFolds2` would allow to bump the Adapt compat. 
Otherwise, could dropping the Referenceables.jl be considered?

**Comment by MasonProtter** [comment]
Hey sorry for the late reply, yeah that should be doable

**Comment by MasonProtter** [comment]
Okay so https://github.com/JuliaFolds2/Referenceables.jl now exists and I've opened a PR for it to be the new source for  the general registry: https://github.com/JuliaRegistries/General/pull/98495

Once that goes through I can tag a new version with Adapt v4 compat (tests already pass with Adapt v4)

**Comment by jeremiedb** [comment]
Thanks for the quick turnaround! Regarding the change of org for Referenceables (https://github.com/JuliaRegistries/General/pull/98495/files), should it include the `.git` at the end of the  repo? 
`repo = "https://github.com/JuliaFolds2/Referenceables.jl.git"`

**Comment by MasonProtter** [comment]
Oops, good catch. Fixed now.

**Comment by MasonProtter** [comment]
Looks like some stuff needs to be fixed for nightly, but that can be done in a separate PR.

**Comment by MasonProtter** [comment]
@jeremiedb this change should be available from the general registry once this PR merges: https://github.com/JuliaRegistries/General/pull/98526

**Pull request merged**
